"use client";

import Link from 'next/link';
import Image from 'next/image';
import AutoGeneratedImage from './AutoGeneratedImage';
import { generateExcerpt } from '@/lib/utils';

interface Post {
  id: number;
  title: string;
  slug: string;
  content: string;
  excerpt?: string;
  featured_image?: string;
  published_at: string;
  updated_at: string;
  is_published: boolean;
  tags?: any[];
}

export default function BlogCard({ post }: { post: Post }) {
  // 使用提供的摘要或从内容生成
  const excerpt = post.excerpt || generateExcerpt(post.content);
  
  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300">
      {/* 暂时屏蔽图片展示
      <div className="relative h-48 w-full">
        {post.featured_image ? (
          <Image
            src={post.featured_image}
            alt={post.title}
            fill
            style={{ objectFit: 'cover' }}
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
          />
        ) : (
          <AutoGeneratedImage
            title={post.title}
            width={400}
            height={200}
            alt={post.title}
          />
        )}
      </div>
      */}
      <div className="p-6">
        <h2 className="text-xl font-bold mb-2 text-gray-800 dark:text-white">{post.title}</h2>
        <p className="text-gray-600 dark:text-gray-300 mb-4 line-clamp-2">{excerpt}</p>
        <div className="flex justify-between items-center">
          <span className="text-sm text-gray-500 dark:text-gray-400">
            {new Date(post.published_at).toLocaleDateString('zh-CN')}
          </span>
          <Link
            href={`/blog/${post.slug}`}
            className="bg-blue-500 hover:bg-blue-600 dark:bg-blue-600 dark:hover:bg-blue-700 text-white px-4 py-2 rounded text-sm transition-colors"
          >
            阅读更多
          </Link>
        </div>
      </div>
    </div>
  );
} 